[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = ['@openzeppelin/contracts=lib/openzeppelin-contracts/contracts']

[fuzz]
runs = 1000
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[rpc_endpoint]
mainnet = "https://mainnet.infura.io/v3/your-infura-key"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
