[package]
name = "testing2"
version = "0.1.0"
edition = "2021"
description = "Online store library"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array_tool = "1.0.3"
