[package]
name = "learning_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = "2.5.0"
tokio = {version = "1.17", features = ["full"]}
criterion = "0.4.0"
rand = "0.8.3"
negative-impl = "0.1.4"

[[bench]]
name = "sorting_benchmark"
harness = false
