[features]
seeds = false
skip-lint = false

[programs.devnet]
chainlink_solana_dapp = "7ABtiu5wEQJLgha9dUE6BvuhH5GPhwyU1aGRtoPAt6Es"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
